previewsEnabled: true

databases:
  - name: jaffle_db
    ipAllowList: []

services:
  - type: pserv
    env: docker
    name: headless-browser
    dockerfilePath: docker/Dockerfile.headless-browser
  - type: web
    env: docker
    name: lightdash
    dockerContext: .
    dockerfilePath: dockerfile-prs
    initialDeployHook: /usr/bin/renderDeployHook.sh
    envVars:
      - key: PGHOST
        fromDatabase:
          name: jaffle_db
          property: host
      - key: PGPORT
        fromDatabase:
          name: jaffle_db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: jaffle_db
          property: database
      - key: PGUSER
        fromDatabase:
          name: jaffle_db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: jaffle_db
          property: password
      - fromGroup: rudder-settings
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: SECURE_COOKIES
        value: true
      - key: TRUST_PROXY
        value: true
      - key: HEADLESS_BROWSER_PORT
        fromService:
          type: pserv
          name: headless-browser
          property: host
      - key: HEADLESS_BROWSER_HOST
        fromService:
          type: pserv
          name: headless-browser
          property: port

envVarGroups:
  - name: rudder-settings
    envVars:
      - key: RUDDERSTACK_WRITE_KEY
        value: 1vikeGadtB0Y0oRDFNL2Prdhkbp
      - key: RUDDERSTACK_DATA_PLANE_URL
        value: https://analytics.lightdash.com
