name: Blueprint progress report
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'packages/frontend/src/**'

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      # Install packages
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      # Count Blueprint & Mantine imports
      - name: Count blueprint imports
        run: |
          EOF="$(openssl rand -hex 8)"
          echo "report<<$EOF" >> $GITHUB_OUTPUT
          yarn ts-node ./scripts/count-blueprint-imports.ts >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        id: generate_report
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          script: |
            const rawOutput = `${{ steps.generate_report.outputs.report }}`
            const message = '<details>\n<summary>Show report</summary>\n\n```\n' + rawOutput.split('\n').slice(2, -1).join('\n') + '\n```\n</details>'
            const title = `## Blueprint refactor progress\n\n`
            const body = title + message
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })
    
